"""Fixed foreign key constraints

Revision ID: c197d1484e10
Revises: 0ea0f59cfbb5
Create Date: 2025-03-06 20:38:13.009387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c197d1484e10'
down_revision: Union[str, None] = '0ea0f59cfbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
