"""Add PCPart and PriceHistory tables

Revision ID: d013f942f7a8
Revises: 427d16c6c5be
Create Date: 2025-03-03 14:14:47.134998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd013f942f7a8'
down_revision: Union[str, None] = '427d16c6c5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pc_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pc_parts_category'), 'pc_parts', ['category'], unique=False)
    op.create_index(op.f('ix_pc_parts_id'), 'pc_parts', ['id'], unique=False)
    op.create_index(op.f('ix_pc_parts_name'), 'pc_parts', ['name'], unique=True)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date_checked', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['pc_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_pc_parts_name'), table_name='pc_parts')
    op.drop_index(op.f('ix_pc_parts_id'), table_name='pc_parts')
    op.drop_index(op.f('ix_pc_parts_category'), table_name='pc_parts')
    op.drop_table('pc_parts')
    # ### end Alembic commands ###
