"""Added Component model

Revision ID: e3766c90449b
Revises: d013f942f7a8
Create Date: 2025-03-05 22:28:26.068188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3766c90449b'
down_revision: Union[str, None] = 'd013f942f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpus')
    op.alter_column('components', 'retailer_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.drop_column('components', 'integrated_graphics')
    op.drop_column('components', 'boost_clock')
    op.drop_column('components', 'image_url')
    op.drop_column('components', 'base_clock')
    op.drop_column('components', 'core_count')
    op.drop_column('components', 'tdp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('tdp', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('core_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('base_clock', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('boost_clock', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('components', sa.Column('integrated_graphics', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.alter_column('components', 'retailer_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('cpus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cores', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_clock', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('boost_clock', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('architecture', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tdp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('integrated_graphics', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cpus_pkey')
    )
    # ### end Alembic commands ###
